config/routes.rb
Rails.application.routes.draw do
  root "todo_lists#index"
  resources :todo_lists do
    resources :todo_tasks do
      member do
        patch :complete
      end
    end
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_tasks
end

app/models/todo_task.rb
class TodoTask < ActiveRecord::Base
  belongs_to :todo_list

  # trueかfalseを返す
  def completed?
    # completed_atが空なら(false)、入っていれば(true)
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @todo_lists = TodoList.all.order("created_at desc")
  end

  def show
    @todo_list = TodoList.find(params[:id])
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save
      redirect_to @todo_list
    end
  end

  def edit
    @todo_list = TodoList.find(params[:id])
  end

  def update
    @todo_list = TodoList.find(params[:id])
    if @todo_list.update(todo_list_params)
      redirect_to @todo_list
    else
      render "edit"
    end
  end

  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy
    redirect_to root_path
  end

  private
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
  before_action :set_todo_list

  def create
    @todo_task = @todo_list.todo_tasks.new(todo_task_params)
    if @todo_task.save
      redirect_to @todo_list
    end
  end

  def complete
    @todo_task = TodoTask.find(params[:id])
    @todo_task.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list
  end

  def destroy
    @todo_task = TodoTask.find(params[:id])
    @todo_task.destroy
    redirect_to @todo_list
  end

  private
    def todo_task_params
      params.require(:todo_task).permit(:task)
    end

    def set_todo_list
      # todo_list_todo_tasks GET /todo_lists/:todo_list_id/todo_tasks(.:format)
      @todo_list = TodoList.find(params[:todo_list_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Todo Task", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#"></a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%= link_to "新規作成", new_todo_list_path, class: "btn navbar-btn btn-success" %>
        <li><a href="#"></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoRevenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/todo_lists/_form.html.erb
<div class="col-md-4">
  <%= simple_form_for @todo_list do |f| %>
    <%= f.input :title, error: "入力は必須です", class: "form-control" %>
    <%= f.input :description, class: "form-control" %>
    <%= f.button "submit", class: "btn btn-success" %>
  <% end %>
</div>

app/views/todo_lists/edit.html.erb
<%= render "form" %>

app/views/todo_lists/index.html.erb
<div class="row">
  <% @todo_lists.each do |todo_list| %>
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= todo_list.title %>
          </h3>
        </div>
        <div class="panel-body">
          <%= todo_list.description %>
        </div>
        <div class="panel-footer">
          <%= link_to "Todoを見る", todo_list, class: "btn btn-block btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/todo_lists/new.html.erb
<%= render "form" %>

app/views/todo_lists/show.html.erb
<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title text-center">
        <%= @todo_list.title %>
      </h3>
    </div>
    <div class="panel-body">
      <%= @todo_list.description %>
    </div>
    <div class="panel-footer">
      <div class="btn-group btn-group-justified">
        <%= link_to edit_todo_list_path, class: "btn btn-warning" do %>
          <i class="fa fa-pencil-square fa-2x"></i>
        <% end %>
        <%= link_to todo_list_path, class: "btn btn-danger", method: :delete, data: { confirm: "よろしいですか？" } do %>
          <i class="fa fa-trash fa-2x"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="col-md-4">
  <%= render @todo_list.todo_tasks %>
</div>

<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Task作成</h3>
    </div>
    <div class="panel-body">
      <%= render "todo_tasks/form" %>
    </div>
  </div>
</div>

app/views/todo_tasks/_form.html.erb
<%= simple_form_for [@todo_list, @todo_list.todo_tasks.build] do |f| %>
  <%= f.input :task, class: "form-control" %>
  <%= f.button "submit", class: "btn btn-success btn-block" %>
<% end %>

app/views/todo_tasks/_todo_task.html.erb
<div class="well well-sm">
  <% if todo_task.completed? %>
    <%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
      <i class="fa fa-check"></i>
    <% end %>
    <strike><%= todo_task.task %></strike>
    <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "よろしい？" }  do %>
      <i class="fa fa-trash"></i>
    <% end %>

  <% else %>
    <%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
      <i class="fa fa-check"></i>
    <% end %>
    <%= todo_task.task %>
    <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "よろしい？" }  do %>
      <i class="fa fa-trash"></i>
    <% end %>
  <% end %>
</div>